// <auto-generated />
using System;
using ECommerce.CouponServiceAPI.Data.ORM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.CouponServiceAPI.Migrations
{
    [DbContext(typeof(CouponSqlServerContext))]
    partial class CouponSqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ECommerce.CouponServiceAPI.Domain.Entities.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("char(20)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_date");

                    b.HasKey("Id");

                    b.HasIndex("CouponCode")
                        .IsUnique();

                    b.ToTable("Coupon", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouponCode = "Coupon_disc_10",
                            CreateDate = new DateTime(2022, 8, 11, 20, 58, 28, 141, DateTimeKind.Local).AddTicks(8754),
                            DiscountAmount = 10m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CouponCode = "Coupon_disc_15",
                            CreateDate = new DateTime(2022, 8, 11, 20, 58, 28, 141, DateTimeKind.Local).AddTicks(8764),
                            DiscountAmount = 15m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CouponCode = "Coupon_disc_20",
                            CreateDate = new DateTime(2022, 8, 11, 20, 58, 28, 141, DateTimeKind.Local).AddTicks(8765),
                            DiscountAmount = 20m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CouponCode = "Coupon_disc_30",
                            CreateDate = new DateTime(2022, 8, 11, 20, 58, 28, 141, DateTimeKind.Local).AddTicks(8766),
                            DiscountAmount = 30m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CouponCode = "Coupon_disc_50",
                            CreateDate = new DateTime(2022, 8, 11, 20, 58, 28, 141, DateTimeKind.Local).AddTicks(8767),
                            DiscountAmount = 50m,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
